# Supabase REST API Configuration
supabase.url=https://wtvxhkcbsfvucncxbyiy.supabase.co
supabase.anon-key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind0dnhoa2Nic2Z2dWNuY3hieWl5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODAzODk5NTksImV4cCI6MjA5NTk2NTk1OX0.OGVa-D_4cueY2Bh7G9xXJOioK0JU1kK2cilvD83oa8A

# Server Configuration
server.port=8080
